	# Load R packages
	cat('Loading R packages...')
	require(limma, quietly = TRUE)
	require(DNAcopy, quietly = TRUE)
	require(preprocessCore, quietly = TRUE)
	require(AMORE, quietly = TRUE)
	require(affy, quietly = TRUE)
	require(robustbase, quietly = TRUE)
	require(mclust, quietly = TRUE)
	require(tcltk, quietly = TRUE)
	require(annotate, quietly = TRUE)
	require(XML, quietly = TRUE)
	require(R2HTML, quietly = TRUE)
	require(plyr, quietly = TRUE)
	require(e1071, quietly = TRUE)
	require(lattice, quietly = TRUE)
	require(foreach, quietly = TRUE)
	require(iterators, quietly = TRUE)
	cat('\tDone\n')
	
	# Load R modules
	cat('Loading CGH workflow...\n')
	source("AllClasses.R")
	cat('All classes... Done.\n')
	source('AllAccessors.R')
	cat('All accessors... Done.\n')
	source('AllShowMethods.R')
	cat('All show methods... Done.\n')
	source('AllGenerics.R')
	cat('All generics... Done.\n')
	source('AllMethods.R')
	cat ('All methods... Done.\n')
	source('AllHelperFunctions.R')
	cat ('Helper functions... Done.\n')
	cat('----------------------------------------\n')
	cat('\tR workflow successfully loaded... !\n')
	cat('----------------------------------------\n')
